### ISSUE TITLE
Shouldn't YUI run after everything else?

### ISSUE THREAD

**Issue by dylang** [mape/connect-assetmanager#1]
hi mape, i'm back for more...  I'm trying to run YUI in the postManipulate group so that it runs just once instead of once per file, and it runs after all the other scripts have done their thing changing the css or js.  

I'm getting a new error about the file being null.  i had to do this because when it runs before it launches a whole bunch of yuicompressors at once and the threads seem to never die, pegging my cpu at 100%.

**Comment by mape** [comment]
The issue with this is that the YUI compressor only takes files as input. So if you want to be able to run YUI compressor on a postHook you need to write a handler that saves the current state into a temporary file and point that to the compressor.

**Comment by mape** [comment]
I've updated connect-assetmanager-handlers so that the YUI compressor hooks now work both as pre and post hook. There is also a path fix in that commit.

It should be noted that if you embed images using base64 into the CSS and run the YUI compressor as a post hook it eats CPU. So I would recommend still running it as a pre hook.

npm update to get the latest version.

**Comment by dylang** [comment]
Excellent, thank you - it's working.  I have my webfonts already embedded, that must be what's screwing up yui.  Commenting out my fonts.css fixed the never-ending java processes.  Maybe I could write a pre-handler to take out anything already embedded and a post-handler to put those items back in.
