### ISSUE TITLE
Safari hangs randomly on page refresh

### ISSUE THREAD

**Issue by mpangrazzi** [mape/connect-assetmanager#35]
Hi,

I've noticed that Safari hangs randomly on page refresh. Using Web Inspector, it seems like CSS and JS file requests remain on 'pending' state, and eventually get a 304 after a lot of time (some minutes).

I've experienced this issue with Safari 5.1.3 and 5.0.3.

**Comment by martnu** [comment]
I am having the same issue with 0.0.27.

**Comment by laurisvan** [comment]
There's a pull request to fix your issue. Since I'm not a github hero I accidentally made it a separate issue #39.

It should work ok for you, though I personally use a custom serveModify function to serve different headers for my assets (my CSS files change seldom, whereas some JS assets change almost constantly and I still want to cache them, at least for a few minutes).
